[2023-12-15T18:07:59.503+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:07:58.086087+00:00/task_id=Create_Table permission to 509
[2023-12-15T18:07:59.506+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:07:58.086087+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:07:58.086087+00:00/task_id=Create_Table'
[2023-12-15T18:07:59.549+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:07:58.086087+00:00/task_id=Create_Table permission to 509
[2023-12-15T18:07:59.550+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:07:58.086087+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:07:58.086087+00:00/task_id=Create_Table'
[2023-12-15T18:07:59.595+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.Create_Table manual__2023-12-15T18:07:58.086087+00:00 [queued]>
[2023-12-15T18:07:59.608+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.Create_Table manual__2023-12-15T18:07:58.086087+00:00 [queued]>
[2023-12-15T18:07:59.609+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-15T18:07:59.629+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): Create_Table> on 2023-12-15 18:07:58.086087+00:00
[2023-12-15T18:07:59.634+0000] {standard_task_runner.py:57} INFO - Started process 1710 to run task
[2023-12-15T18:07:59.638+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'Create_Table', 'manual__2023-12-15T18:07:58.086087+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmpe2a1lhqx']
[2023-12-15T18:07:59.639+0000] {standard_task_runner.py:85} INFO - Job 84: Subtask Create_Table
[2023-12-15T18:07:59.695+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:07:58.086087+00:00/task_id=Create_Table permission to 509
[2023-12-15T18:07:59.697+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:07:58.086087+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:07:58.086087+00:00/task_id=Create_Table'
[2023-12-15T18:07:59.700+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.Create_Table manual__2023-12-15T18:07:58.086087+00:00 [running]> on host d739bc9bef06
[2023-12-15T18:07:59.814+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='Create_Table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-15T18:07:58.086087+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-15T18:07:58.086087+00:00'
[2023-12-15T18:07:59.815+0000] {sql.py:274} INFO - Executing: <function createTableSQL at 0x7f1d944461f0>
[2023-12-15T18:07:59.828+0000] {base.py:73} INFO - Using connection ID 'neonServerDB-Postgres' for task execution.
[2023-12-15T18:07:59.837+0000] {base.py:73} INFO - Using connection ID 'neonServerDB-Postgres' for task execution.
[2023-12-15T18:08:05.303+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    for sql_statement in sql_list:
TypeError: 'function' object is not iterable
[2023-12-15T18:08:05.338+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality, task_id=Create_Table, execution_date=20231215T180758, start_date=20231215T180759, end_date=20231215T180805
[2023-12-15T18:08:05.368+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 84 for task Create_Table ('function' object is not iterable; 1710)
[2023-12-15T18:08:05.396+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-15T18:08:05.441+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
