[2023-12-15T18:20:01.483+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:20:00.031743+00:00/task_id=Create_Table permission to 509
[2023-12-15T18:20:01.485+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:20:00.031743+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:20:00.031743+00:00/task_id=Create_Table'
[2023-12-15T18:20:01.552+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:20:00.031743+00:00/task_id=Create_Table permission to 509
[2023-12-15T18:20:01.553+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:20:00.031743+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:20:00.031743+00:00/task_id=Create_Table'
[2023-12-15T18:20:01.631+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.Create_Table manual__2023-12-15T18:20:00.031743+00:00 [queued]>
[2023-12-15T18:20:01.651+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.Create_Table manual__2023-12-15T18:20:00.031743+00:00 [queued]>
[2023-12-15T18:20:01.652+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-15T18:20:01.679+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): Create_Table> on 2023-12-15 18:20:00.031743+00:00
[2023-12-15T18:20:01.687+0000] {standard_task_runner.py:57} INFO - Started process 1897 to run task
[2023-12-15T18:20:01.694+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'Create_Table', 'manual__2023-12-15T18:20:00.031743+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmpxwy6w5u_']
[2023-12-15T18:20:01.696+0000] {standard_task_runner.py:85} INFO - Job 91: Subtask Create_Table
[2023-12-15T18:20:01.780+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:20:00.031743+00:00/task_id=Create_Table permission to 509
[2023-12-15T18:20:01.782+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:20:00.031743+00:00/task_id=Create_Table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=manual__2023-12-15T18:20:00.031743+00:00/task_id=Create_Table'
[2023-12-15T18:20:01.785+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.Create_Table manual__2023-12-15T18:20:00.031743+00:00 [running]> on host d739bc9bef06
[2023-12-15T18:20:01.955+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='Create_Table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-15T18:20:00.031743+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-15T18:20:00.031743+00:00'
[2023-12-15T18:20:01.957+0000] {sql.py:274} INFO - Executing: <function createTableSQL at 0x7f1d9445aa60>
[2023-12-15T18:20:01.982+0000] {base.py:73} INFO - Using connection ID 'neonServerDB-Postgres' for task execution.
[2023-12-15T18:20:01.997+0000] {base.py:73} INFO - Using connection ID 'neonServerDB-Postgres' for task execution.
[2023-12-15T18:20:06.477+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    for sql_statement in sql_list:
TypeError: 'function' object is not iterable
[2023-12-15T18:20:06.525+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality, task_id=Create_Table, execution_date=20231215T182000, start_date=20231215T182001, end_date=20231215T182006
[2023-12-15T18:20:06.580+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 91 for task Create_Table ('function' object is not iterable; 1897)
[2023-12-15T18:20:06.622+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-15T18:20:06.713+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
