[2023-12-17T11:18:33.549+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509
[2023-12-17T11:18:33.553+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform'
[2023-12-17T11:18:33.650+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509
[2023-12-17T11:18:33.654+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform'
[2023-12-17T11:18:33.828+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.Transform scheduled__2023-12-01T04:00:00+00:00 [queued]>
[2023-12-17T11:18:33.878+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.Transform scheduled__2023-12-01T04:00:00+00:00 [queued]>
[2023-12-17T11:18:33.879+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-17T11:18:33.961+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Transform> on 2023-12-01 04:00:00+00:00
[2023-12-17T11:18:33.973+0000] {standard_task_runner.py:57} INFO - Started process 2056 to run task
[2023-12-17T11:18:33.996+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'Transform', 'scheduled__2023-12-01T04:00:00+00:00', '--job-id', '327', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmptlmxuf83']
[2023-12-17T11:18:34.016+0000] {standard_task_runner.py:85} INFO - Job 327: Subtask Transform
[2023-12-17T11:18:34.260+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509
[2023-12-17T11:18:34.264+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform'
[2023-12-17T11:18:34.267+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.Transform scheduled__2023-12-01T04:00:00+00:00 [running]> on host 1a58977f5573
[2023-12-17T11:18:34.729+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='Transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T04:00:00+00:00'
[2023-12-17T11:18:38.201+0000] {python.py:194} INFO - Done. Returned value was:       city country unit  last_value       lat         lng
0  Jakarta      ID   o3      -0.999 -6.182536  106.834236
[2023-12-17T11:18:38.383+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=air_quality, task_id=Transform, execution_date=20231201T040000, start_date=20231217T111833, end_date=20231217T111838
[2023-12-17T11:18:38.639+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-17T11:18:38.825+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-28T16:51:37.484+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509
[2023-12-28T16:51:37.489+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform'
[2023-12-28T16:51:37.566+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509
[2023-12-28T16:51:37.568+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform'
[2023-12-28T16:51:37.673+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.Transform scheduled__2023-12-01T04:00:00+00:00 [queued]>
[2023-12-28T16:51:37.704+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.Transform scheduled__2023-12-01T04:00:00+00:00 [queued]>
[2023-12-28T16:51:37.709+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-28T16:51:37.896+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Transform> on 2023-12-01 04:00:00+00:00
[2023-12-28T16:51:37.909+0000] {standard_task_runner.py:57} INFO - Started process 163 to run task
[2023-12-28T16:51:37.932+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'Transform', 'scheduled__2023-12-01T04:00:00+00:00', '--job-id', '835', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmpkicpiq36']
[2023-12-28T16:51:37.939+0000] {standard_task_runner.py:85} INFO - Job 835: Subtask Transform
[2023-12-28T16:51:38.220+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509
[2023-12-28T16:51:38.225+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform'
[2023-12-28T16:51:38.234+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.Transform scheduled__2023-12-01T04:00:00+00:00 [running]> on host d67dd4682ccf
[2023-12-28T16:51:38.664+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='Transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T04:00:00+00:00'
[2023-12-28T16:51:40.848+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "xcom" violates foreign key constraint "xcom_task_instance_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(air_quality, Transform, scheduled__2023-12-01T04:00:00+00:00, -1) is not present in table "task_instance".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airQuality.py", line 81, in transformation
    ti.xcom_push(key='Transformed', value=dt)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2479, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 273, in set
    session.flush()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "xcom" violates foreign key constraint "xcom_task_instance_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(air_quality, Transform, scheduled__2023-12-01T04:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO xcom (dag_run_id, task_id, map_index, key, dag_id, run_id, value, timestamp) VALUES (%(dag_run_id)s, %(task_id)s, %(map_index)s, %(key)s, %(dag_id)s, %(run_id)s, %(value)s, %(timestamp)s)]
[parameters: {'dag_run_id': 168, 'task_id': 'Transform', 'map_index': -1, 'key': 'Transformed', 'dag_id': 'air_quality', 'run_id': 'scheduled__2023-12-01T04:00:00+00:00', 'value': <psycopg2.extensions.Binary object at 0x7f31b665cb40>, 'timestamp': datetime.datetime(2023, 12, 28, 16, 51, 40, 721812, tzinfo=Timezone('UTC'))}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-12-28T16:51:41.064+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=air_quality, task_id=Transform, execution_date=20231201T040000, start_date=20231228T165137, end_date=20231228T165140
[2023-12-28T16:51:41.160+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 835 for task Transform ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(air_quality, Transform, scheduled__2023-12-01T04:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'Transform', 'dag_id': 'air_quality', 'run_id': 'scheduled__2023-12-01T04:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2023, 12, 28, 16, 51, 37, 674618, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2023, 12, 28, 16, 51, 40, 994912, tzinfo=Timezone('UTC')), 'duration': 3}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 163)
[2023-12-28T16:51:41.253+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-28T16:54:13.062+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509
[2023-12-28T16:54:13.072+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform'
[2023-12-28T16:54:13.280+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509
[2023-12-28T16:54:13.283+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform'
[2023-12-28T16:54:13.507+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality.Transform scheduled__2023-12-01T04:00:00+00:00 [queued]>
[2023-12-28T16:54:13.601+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality.Transform scheduled__2023-12-01T04:00:00+00:00 [queued]>
[2023-12-28T16:54:13.609+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-28T16:54:13.735+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Transform> on 2023-12-01 04:00:00+00:00
[2023-12-28T16:54:13.748+0000] {standard_task_runner.py:57} INFO - Started process 869 to run task
[2023-12-28T16:54:13.794+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'air_quality', 'Transform', 'scheduled__2023-12-01T04:00:00+00:00', '--job-id', '1042', '--raw', '--subdir', 'DAGS_FOLDER/airQuality.py', '--cfg-path', '/tmp/tmps3zv4km4']
[2023-12-28T16:54:13.820+0000] {standard_task_runner.py:85} INFO - Job 1042: Subtask Transform
[2023-12-28T16:54:14.202+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509
[2023-12-28T16:54:14.203+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=air_quality/run_id=scheduled__2023-12-01T04:00:00+00:00/task_id=Transform'
[2023-12-28T16:54:14.218+0000] {task_command.py:416} INFO - Running <TaskInstance: air_quality.Transform scheduled__2023-12-01T04:00:00+00:00 [running]> on host d67dd4682ccf
[2023-12-28T16:54:14.742+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ghifari' AIRFLOW_CTX_DAG_ID='air_quality' AIRFLOW_CTX_TASK_ID='Transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T04:00:00+00:00'
[2023-12-28T16:54:17.991+0000] {python.py:194} INFO - Done. Returned value was:       city country unit  last_value       lat         lng
0  Jakarta      ID   o3      -0.999 -6.182536  106.834236
[2023-12-28T16:54:18.207+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=air_quality, task_id=Transform, execution_date=20231201T040000, start_date=20231228T165413, end_date=20231228T165418
[2023-12-28T16:54:18.735+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-28T16:54:18.837+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
